from app.models.schemas import PRResponse

class ReportService:
    @staticmethod
    def generate_markdown(response: PRResponse, title: str) -> str:
        md = f"# PRettySus Analysis Report: {title}\n\n"
        
        # Top-level scores
        md += f"**Repository Memory Integrity:** {response.repositoryMemoryIntegrity.score}/100 ({response.repositoryMemoryIntegrity.riskLevel.upper()} RISK)\n\n"
        md += f"**Base PR Score:** {response.score}/100 ({response.riskLevel.upper()} RISK)\n\n"
        
        md += f"*{response.summary}*\n\n"
        md += "---\n\n"
        
        # Main Branch Sentry
        md += "## Main Branch Sentry\n"
        status = "✅ SAFE TO MERGE" if response.mainBranchSentry.isMainBranchSafe else "❌ UNSAFE FOR MAIN BRANCH"
        md += f"**Status:** {status}\n\n"
        md += f"{response.mainBranchSentry.historyRiskExplanation}\n\n"
        
        if response.mainBranchSentry.failedChecks:
            md += "### Failed Checks:\n"
            for check in response.mainBranchSentry.failedChecks:
                md += f"- ❌ {check}\n"
            md += "\n"
            
        # Communication Coverage
        md += "## Communication Coverage\n"
        md += f"**Coverage:** {response.communicationCoverage.weightedPercentage}% (Weighted)\n\n"
        if response.communicationCoverage.highImpactUncoveredEntities:
            md += "### 🚨 High-Impact Missing Explanations\n"
            md += f"`{'`, `'.join(response.communicationCoverage.highImpactUncoveredEntities)}`\n\n"
            
        # Squash Analysis
        md += "## Squash & Merge Analysis\n"
        md += f"- **Squash Noise Score:** {response.squashAnalysis.squashNoiseScore}%\n"
        md += f"- **Duplicate Commits:** {response.squashAnalysis.duplicateMessageCount}\n"
        md += f"- **Generic Commits:** {response.squashAnalysis.genericMessageCount}\n\n"
        
        if response.squashAnalysis.buriedSignalMessages:
            md += "### 💎 Buried Signal (High-Value Commits Lost in Noise)\n"
            for msg in response.squashAnalysis.buriedSignalMessages:
                md += f"- {msg}\n"
            md += "\n"
            
        md += "### Deterministic Suggested Summary\n"
        md += "*(Generated entirely without AI using diff analysis and high-impact coverage maps)*\n"
        md += "```text\n"
        md += response.squashAnalysis.recommendedFinalSummary
        md += "\n```\n\n"
        
        # Policy Violations
        if response.policyViolations:
            md += "## 🛡️ Critical Policy Violations\n"
            for pv in response.policyViolations:
                md += f"- **{pv.policy}:** {pv.violation}\n"
            md += "\n"
            
        # Recommendations
        if response.recommendations:
            md += "## 💡 Recommendations\n"
            for rec in response.recommendations:
                md += f"- {rec}\n"
            md += "\n"
            
        md += "---\n*Generated by PRettySus — Static Analysis for Engineering Communication*"
        return md
